# Global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 15s
  external_labels:
    cluster: prometheus-single
    region: europe
    environment: dev

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']

  - job_name: 'https-prometheus'
    scheme: https
    static_configs:
    - targets: ['python-app-route-scenario-2.apps.cluster-gwt45.gwt45.sandbox265.opentlc.com']
