{
 "title": "Custom",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(process_cpu_seconds_total)" }
   ]
  },
  {
   "title": "Arbitrary Counter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(arbitrary_counter_total)" }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "targets": [
    { "expr": "python_gc_collections_total" }
   ]
  },
  {
   "title": "Total Resident Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes) / 10000000"
    }
   ]
  },
  {
   "title": "Total GET Requests /",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"/\",method=\"GET\",status=\"2xx\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}